<?php
    namespace App\Model\Table;

    use Cake\ORM\Table;
    use Cake\ORM\Query;
    use Cake\ORM\RulesChecker;
    use Cake\Validation\Validator;

    class UsersTable extends Table
    {
        public function initialize(array $config): void
        {
            parent::initialize($config); // TODO: Change the autogenerated stub

            $this->setTable('users');

            $this->addBehavior('Timestamp');
        }

        public function validationDefault(Validator $validator): Validator
        {
            $validator->requirePresence('name', 'create')->notEmptyString('name');
            $validator->requirePresence('email', 'create')->notEmptyString('email');
            $validator->requirePresence('username', 'create')->notEmptyString('username');
            $validator->requirePresence('password', 'create')->notEmptyString('password')
                                                             ->minLength('password', 6);

            return $validator;
        }

        public function buildRules(RulesChecker $rules): RulesChecker
        {
            // Add a rule that is applied for create and update operations
            $rules->add($rules->isUnique(['email'], 'Este e-mail já está sendo utilizado!'));
            $rules->add($rules->isUnique(['username'], 'Este username já está sendo utilizado!'));

            return $rules;
        }
    }
